In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "customer_name": ["Asta", "Mantas", "Ieva", "Tomas"],
    "segment": ["Retail", "Retail", "Business", "Retail"]
})
 
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 2, 3, 5],  # customer_id=5 neturi atitikmens customers lentelėje
    "product_id": [10, 10, 11, 12, 12],
    "quantity": [1, 2, 1, 3, 1]
})
 
products = pd.DataFrame({
    "product_id": [10, 11, 12],
    "product_name": ["Bike", "Helmet", "Bottle"],
    "unit_price": [800, 50, 12]
})
 
customers, orders, products

(   customer_id customer_name   segment
 0            1          Asta    Retail
 1            2        Mantas    Retail
 2            3          Ieva  Business
 3            4         Tomas    Retail,
    order_id  customer_id  product_id  quantity
 0       101            1          10         1
 1       102            2          10         2
 2       103            2          11         1
 3       104            3          12         3
 4       105            5          12         1,
    product_id product_name  unit_price
 0          10         Bike         800
 1          11       Helmet          50
 2          12       Bottle          12)

In [6]:
# INNER JOIN: užsakymai + klientai (paliekami tik tie užsakymai, kurių klientas egzistuoja customers lentelėje)
orders_inner = orders.merge(customers, on="customer_id", how="inner")
orders_inner

   order_id  customer_id  product_id  quantity customer_name   segment
0       101            1          10         1          Asta    Retail
1       102            2          10         2        Mantas    Retail
2       103            2          11         1        Mantas    Retail
3       104            3          12         3          Ieva  Business

In [7]:
# LEFT JOIN: paliekami visi užsakymai, net jei klientas nerandamas
orders_left = orders.merge(customers, on="customer_id", how="left")
orders_left

   order_id  customer_id  product_id  quantity customer_name   segment
0       101            1          10         1          Asta    Retail
1       102            2          10         2        Mantas    Retail
2       103            2          11         1        Mantas    Retail
3       104            3          12         3          Ieva  Business
4       105            5          12         1           NaN       NaN

In [8]:
# Paruošiamas indeksas
customers_idx = customers.set_index("customer_id")
 
# join pagal customer_id (iš orders pusės)
orders_join = orders.join(customers_idx, on="customer_id", how="left")
orders_join

   order_id  customer_id  product_id  quantity customer_name   segment
0       101            1          10         1          Asta    Retail
1       102            2          10         2        Mantas    Retail
2       103            2          11         1        Mantas    Retail
3       104            3          12         3          Ieva  Business
4       105            5          12         1           NaN       NaN

In [9]:
orders_enriched = (
    orders
    .merge(customers, on="customer_id", how="left")
    .merge(products, on="product_id", how="left")
)
 
 
orders_enriched

,order_id,customer_id,product_id,quantity,customer_name,segment,product_name,unit_price
0,101,1,10,1,Asta,Retail,Bike,800
1,102,2,10,2,Mantas,Retail,Bike,800
2,103,2,11,1,Mantas,Retail,Helmet,50
3,104,3,12,3,Ieva,Business,Bottle,12
4,105,5,12,1,NaN,NaN,Bottle,12

In [10]:
orders_enriched["revenue"] = (orders_enriched["quantity"] * orders_enriched["unit_price"]).round(2)
 
orders_enriched

,order_id,customer_id,product_id,quantity,customer_name,segment,product_name,unit_price,revenue
0,101,1,10,1,Asta,Retail,Bike,800,800
1,102,2,10,2,Mantas,Retail,Bike,800,1600
2,103,2,11,1,Mantas,Retail,Helmet,50,50
3,104,3,12,3,Ieva,Business,Bottle,12,36
4,105,5,12,1,NaN,NaN,Bottle,12,12